homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 39.2116
  longitude: -94.5739
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 307
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  #Uncomment this to add a password (recommended!)
  api_password: !secret api_pass
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: dhass.duckdns.org:443

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

wink:
  email: !secret wink_email
  password: !secret wink_pass
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret
    
envisalink:
  host: !secret envisalink_ip
  panel_type: !secret envisalink_panel
  user_name: !secret envisalink_user
  password: !secret envisalink_pass
  code: !secret envisalink_code
  port: !secret envisalink_port
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30
  #panic_type: Police
  zones:
    01:
      name: 'Garage Door'
      type: 'opening'
    02:
      name: 'Back Door'
      type: 'opening'
    03:
      name: 'Front Door'
      type: 'opening'
    04:
      name: 'Kitchen Door'
      type: 'opening'
  partitions:
    1:
      name: 'Home'    
